#!/usr/bin/env python3
# Status: production
# Path: Caddy reverse-proxy
"""
HTTPS reverse proxy that rotates Gemini API keys per request.

SLOC-exempt: 458 lines — single cohesive reverse proxy (TLS termination → key rotation
→ request forwarding → response relay). Request handler, KeyRotator integration,
and model routing form one inseparable HTTP proxy loop.

Listens on a local port with a self-signed cert for generativelanguage.googleapis.com.
Each incoming request gets a fresh API key picked via KeyRotator.
"""

import json
import os
import socket
import ssl
import sys
import threading
from http.server import HTTPServer, BaseHTTPRequestHandler
from typing import Optional

from lib.auth.key_rotator import KeyRotator
from lib.auth.key_loader import load_api_keys, STATE_FILE

LISTEN_HOST = "127.0.0.1"
LISTEN_PORT = 4430
REAL_HOST = "generativelanguage.googleapis.com"
REAL_PORT = 443

CERT_FILE = os.path.expanduser("~/.local/share/devforge/certs/proxy-cert.pem")
KEY_FILE = os.path.expanduser("~/.local/share/devforge/certs/proxy-key.pem")

_rotator: Optional[KeyRotator] = None
_lock = threading.Lock()

def _get_rotator() -> KeyRotator:
    global _rotator
    if _rotator is not None:
        return _rotator

    keys = load_api_keys()
    if not keys:
        raise RuntimeError("No API keys found")

    rotator = KeyRotator(keys)
    if os.path.exists(STATE_FILE):
        try:
            with open(STATE_FILE) as f:
                s = json.load(f)
            rotator._calls = {int(k): v for k, v in s.get("calls", {}).items()}
            rotator._fails = {int(k): v for k, v in s.get("fails", {}).items()}
            rotator._last_used = {int(k): v for k, v in s.get("last_used", {}).items()}
            rotator._backoff_until = {int(k): v for k, v in s.get("backoff_until", {}).items()}
        except Exception:
            pass

    _rotator = rotator
    return rotator


def _save_state(rotator: KeyRotator):
    os.makedirs(os.path.dirname(STATE_FILE), exist_ok=True)
    state = {
        "calls": rotator._calls,
        "fails": rotator._fails,
        "last_used": rotator._last_used,
        "backoff_until": rotator._backoff_until,
    }
    with open(STATE_FILE + ".tmp", "w") as f:
        json.dump(state, f)
    os.rename(STATE_FILE + ".tmp", STATE_FILE)


REAL_IPS = ["142.250.21.95", "142.250.23.95", "142.251.24.95", "142.251.23.95"]
CURRENT_REAL_IP = REAL_IPS[0]


def _resolve_real_ip() -> str:
    """Return the real Google API IP, bypassing any hosts file redirect."""
    return CURRENT_REAL_IP


# Tiered routing to spread quota across free models:
#   Simple queries → flash (gemini-2.5-flash, generous free tier)
#   Complex queries → gemma-4-31b-it (primary, ~11s)
#   31B exhausted → pro (gemini-2.5-pro, ~50/day)
#   Pro exhausted → gemma-4-26b-a4b-it (spare, ~27s, last resort)
#   26B exhausted → flash (final fallback)

COMPLEX_KEYWORDS = [
    "코드", "구현", "디버그", "분석", "설계", "리팩토링",
    "설명", "해결", "찾아", "검색", "비교", "최적화",
    "code", "implement", "debug", "analyze", "design", "refactor",
    "explain", "solve", "search", "compare", "optimize",
    "function", "class", "bug", "error", "fix", "test",
    "review", "security", "performance",
]

LIGHT_KEYWORDS = [
    "뭐야", "안녕", "짧게", "번역", "날씨", "몇 시",
    "what is", "hi", "hello", "translate", "weather", "time",
    "간단", "한 줄", "한 문장", "3단어",
]

GEMMA_26B_MODEL = "gemma-4-26b-a4b-it"
GEMMA_31B_MODEL = "gemma-4-31b-it"
PRO_MODEL = "gemini-2.5-pro"
FLASH_MODEL = "gemini-2.5-flash"

# DevForge server rules injected into systemInstruction of every request.
# This works around Cline 3.0.8 not loading filesystem rules in CLI mode.
# Rules auto-generated by sync_gemini_rules.py from infrastructure.md + llm-common-rule.md.
# The header section (~/.gemini/header.md) is stripped — only the operational rules body.
_RULES_FILE = os.path.expanduser("~/GEMINI.md")

def _load_rules() -> str:
    try:
        with open(_RULES_FILE) as f:
            content = f.read()
        # Split at the last "---" separator (end of header section)
        # Header ends with "---\\n", body starts with infrastructure.md + llm-common-rule.md content
        idx = content.rfind("\n---\n")
        if idx != -1:
            body = content[idx + 5:].strip()
        else:
            body = content.strip()
        # Wrap for Gemini — mark as system-level instructions
        return f"[DevForge Server Rules — auto-synced from common-*.md]\n\n{body}" if body else "[DevForge Server Rules — empty]"
    except Exception:
        return "[DevForge Server Rules — GEMINI.md not found. Run sync_gemini_rules.py]"

DEVFORTE_SYSTEM_RULES = _load_rules()


def _pick_gemma() -> str:
    """Return 31B as primary Gemma. 26B is spare, only via fallback on 429."""
    return GEMMA_31B_MODEL


def _extract_text(part: dict) -> str:
    """Recursively extract all text from a Gemini content part."""
    texts = []
    if "text" in part:
        texts.append(part["text"])
    if "functionCall" in part:
        fc = part["functionCall"]
        texts.append(fc.get("name", ""))
        texts.append(str(fc.get("args", "")))
    if "functionResponse" in part:
        fr = part["functionResponse"]
        texts.append(fr.get("name", ""))
        texts.append(str(fr.get("response", "")))
    return " ".join(texts)


def classify_query_intent(data: dict, current_model: str) -> str:
    """Return the best model for this request.

    Tiered strategy:
    - Light keyword matches → flash (short-circuit)
    - Complex (keywords + length + tools) → gemma 26B/31B alternating
    - Default → flash
    - Pro is NOT auto-selected; it's only a fallback on 429.
    """
    contents = data.get("contents", [])
    if not contents:
        return current_model

    total_text = ""
    tool_count = 0
    for c in contents[-6:]:
        for p in c.get("parts", []):
            total_text += _extract_text(p) + " "
            if "functionCall" in p or "functionResponse" in p:
                tool_count += 1

    total_text_lower = total_text.lower()

    # Simple queries → flash (short-circuit)
    light_score = sum(1 for kw in LIGHT_KEYWORDS if kw in total_text_lower)
    if light_score >= 2:
        return FLASH_MODEL

    # Complex signals
    complex_score = 0
    for kw in COMPLEX_KEYWORDS:
        if kw in total_text_lower:
            complex_score += 1

    if len(total_text) > 4000:
        complex_score += 2

    if tool_count >= 3:
        complex_score += 2

    # High complexity → gemma (alternating 26B/31B)
    if complex_score >= 3:
        return _pick_gemma()

    return FLASH_MODEL


def _is_gemma_model(path: str) -> bool:
    return GEMMA_26B_MODEL in path or GEMMA_31B_MODEL in path


class ProxyHandler(BaseHTTPRequestHandler):
    def _pick_key(self):
        with _lock:
            rotator = _get_rotator()
            picked = rotator.pick()
            if picked is None:
                return None, None, None
            idx, name, key = picked
            _save_state(rotator)
            return name, key, idx

    def _make_request(self, method, path, headers, body, key):
        """Make one HTTPS request to the upstream API. Returns (status_code, rest_lines, raw_body)."""
        real_ip = _resolve_real_ip()
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        context = ssl.create_default_context()
        wrapped = context.wrap_socket(sock, server_hostname=REAL_HOST)
        wrapped.connect((real_ip, REAL_PORT))

        header_lines = [f"{method} {path} HTTP/1.1"]
        header_lines.append(f"Host: {REAL_HOST}")
        for k, v in headers.items():
            if k.lower() not in ("host",):
                header_lines.append(f"{k}: {v}")
        header_lines.append("Connection: close")
        req = "\r\n".join(header_lines) + "\r\n\r\n"
        wrapped.sendall(req.encode())
        if body:
            wrapped.sendall(body)

        wrapped.settimeout(30)
        response_data = b""
        try:
            while True:
                chunk = wrapped.recv(65536)
                if not chunk:
                    break
                response_data += chunk
        except socket.timeout:
            pass
        finally:
            wrapped.close()

        header_end = response_data.find(b"\r\n\r\n")
        if header_end == -1:
            return 502, [], b""
        raw_headers = response_data[:header_end]
        raw_body = response_data[header_end + 4:]
        status_line, *rest = raw_headers.decode(errors="replace").split("\r\n")
        status_code = int(status_line.split(" ")[1])
        return status_code, rest, raw_body

    def _dechunk(self, rest_lines, raw_body):
        """Dechunk transfer-encoded response body. Returns unencoded bytes."""
        is_chunked = False
        for line in rest_lines:
            if ":" in line:
                k, v = line.split(":", 1)
                if k.lower() == "transfer-encoding" and "chunked" in v.lower():
                    is_chunked = True
        if not is_chunked:
            return raw_body

        resp_body = b""
        pos = 0
        while pos < len(raw_body):
            chunk_end = raw_body.find(b"\r\n", pos)
            if chunk_end == -1:
                break
            try:
                chunk_size = int(raw_body[pos:chunk_end], 16)
            except ValueError:
                break
            if chunk_size == 0:
                break
            pos = chunk_end + 2
            resp_body += raw_body[pos:pos + chunk_size]
            pos += chunk_size + 2
        return resp_body

    def proxy_request_with_fallback(self, method):
        name, key, idx = self._pick_key()
        if key is None:
            self.send_error(503, "No API keys available")
            return

        content_length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(content_length) if content_length else None

        path = self.path
        req_headers = dict(self.headers)
        req_headers.pop("Host", None)

        # Patch 1: fix empty function_response.name for Cline Gemini compatibility.
        # Patch 2: auto-select model based on request complexity.
        if body:
            try:
                data = json.loads(body)
                # --- Patch 1: function_response.name ---
                for content in data.get("contents", []):
                    for part in content.get("parts", []):
                        fr = part.get("functionResponse")
                        if fr is not None and not fr.get("name"):
                            fr["name"] = fr.get("id", "tool-response")
                body = json.dumps(data).encode()

                # --- Patch 2: model routing ---
                req_model = "gemini-2.5-flash"
                if "/models/" in self.path:
                    rest = self.path.split("/models/", 1)[1]
                    req_model = rest.split(":")[0] if ":" in rest else req_model

                chosen = req_model
                if "flash" in req_model:
                    chosen = classify_query_intent(data, req_model)
                    if chosen != req_model:
                        path = self.path.replace(req_model, chosen)
                        print(f"[proxy] model: {req_model} → {chosen}  [KeyRotator: {name}]", file=sys.stderr)

                # --- Patch 3: systemInstruction — only for models that support it ---
                # gemini-2.5-flash (free tier) does NOT support systemInstruction.
                # Strip it from the body even if the CLI sent it (e.g. from GEMINI.md).
                if "flash" in chosen:
                    data.pop("systemInstruction", None)
                else:
                    sys_instr = data.get("systemInstruction", {})
                    sys_parts = sys_instr.get("parts", [])
                    existing_text = " ".join(p.get("text", "") for p in sys_parts)
                    if "DevForge Server Rules" not in existing_text:
                        sys_parts.insert(0, {"text": DEVFORTE_SYSTEM_RULES})
                        data["systemInstruction"] = {"parts": sys_parts}

                body = json.dumps(data).encode()
            except Exception:
                pass

        if "Content-Length" in req_headers:
            req_headers["Content-Length"] = str(len(body)) if body else "0"
        req_headers["x-goog-api-key"] = key

        status_code, rest_lines, raw_body = self._make_request(method, path, req_headers, body, key)

        if status_code == 429 and _is_gemma_model(path):
            if GEMMA_31B_MODEL in path:
                # 31B exhausted → pro
                fallback_path = path.replace(GEMMA_31B_MODEL, PRO_MODEL)
                print(f"[proxy] 31B quota exhausted → pro  [KeyRotator: {name}]", file=sys.stderr)
                status_code, rest_lines, raw_body = self._make_request(method, fallback_path, req_headers, body, key)

                if status_code == 429:
                    # Pro exhausted → 26B (spare)
                    fallback_path = fallback_path.replace(PRO_MODEL, GEMMA_26B_MODEL)
                    print(f"[proxy] pro exhausted → 26B (spare)  [KeyRotator: {name}]", file=sys.stderr)
                    status_code, rest_lines, raw_body = self._make_request(method, fallback_path, req_headers, body, key)

                    if status_code == 429:
                        # 26B exhausted → flash
                        fallback_path = fallback_path.replace(GEMMA_26B_MODEL, FLASH_MODEL)
                        print(f"[proxy] 26B exhausted → flash  [KeyRotator: {name}]", file=sys.stderr)
                        status_code, rest_lines, raw_body = self._make_request(method, fallback_path, req_headers, body, key)
            elif GEMMA_26B_MODEL in path:
                # 26B (spare) exhausted → flash
                fallback_path = path.replace(GEMMA_26B_MODEL, FLASH_MODEL)
                print(f"[proxy] 26B exhausted → flash  [KeyRotator: {name}]", file=sys.stderr)
                status_code, rest_lines, raw_body = self._make_request(method, fallback_path, req_headers, body, key)

        elif status_code == 429 and PRO_MODEL in path and FLASH_MODEL not in path:
            # Direct pro call (not from gemma fallback) → flash
            print(f"[proxy] pro quota exhausted → flash  [KeyRotator: {name}]", file=sys.stderr)
            fallback_path = path.replace(PRO_MODEL, FLASH_MODEL)
            status_code, rest_lines, raw_body = self._make_request(method, fallback_path, req_headers, body, key)

        # Flash 429 — retry with other keys (each key has independent daily quota)
        if status_code == 429 and ("flash" in path):
            for retry_no in range(min(2, max(1, len(_get_rotator().keys) - 1))):
                with _lock:
                    rotator = _get_rotator()
                    rotator.rate_limited(idx, 60)
                    picked = rotator.pick()
                    if picked is None or picked[0] == idx:
                        break
                    new_idx, new_name, new_key = picked
                    _save_state(rotator)
                print(f"[proxy] flash 429 ({retry_no+1}) → retry w/ {new_name}", file=sys.stderr)
                idx, name = new_idx, new_name
                req_headers["x-goog-api-key"] = new_key
                status_code, rest_lines, raw_body = self._make_request(method, path, req_headers, body, new_key)
                if status_code != 429:
                    break

        resp_body = self._dechunk(rest_lines, raw_body)

        # Intercept 503 (server overload) with clear Korean message
        if status_code == 503:
            self.send_response(503)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.end_headers()
            msg = json.dumps({
                "error": {
                    "code": 503,
                    "message": "Google 서버 과부하입니다. 잠시 후에 다시 시도해주세요.",
                    "status": "UNAVAILABLE"
                }
            }, ensure_ascii=False)
            self.wfile.write(msg.encode())
            print(f"[proxy] {name} → {status_code} (overload — 한글 안내)", file=sys.stderr)
            return

        self.send_response(status_code)
        for line in rest_lines:
            if ":" in line:
                k, v = line.split(":", 1)
                if k.lower() not in ("transfer-encoding", "connection"):
                    self.send_header(k.strip(), v.strip())
        self.end_headers()

        if resp_body:
            self.wfile.write(resp_body)

        # Record stats
        with _lock:
            rotator = _get_rotator()
            if status_code in (200, 201):
                rotator.success(idx)
            elif status_code == 429:
                rotator.rate_limited(idx, 60)
            _save_state(rotator)

        print(f"[proxy] {name} → {status_code} {self.path[:60]}", file=sys.stderr)

    def do_POST(self):
        self.proxy_request_with_fallback("POST")

    def do_GET(self):
        self.proxy_request_with_fallback("GET")

    def do_PUT(self):
        self.proxy_request_with_fallback("PUT")

    def do_DELETE(self):
        self.proxy_request_with_fallback("DELETE")

    def do_PATCH(self):
        self.proxy_request_with_fallback("PATCH")

    def log_message(self, format, *args):
        pass  # suppress default logging


def main():
    import signal

    def shutdown(signum, frame):
        print("\n[proxy] shutting down...", file=sys.stderr)
        sys.exit(0)

    signal.signal(signal.SIGTERM, shutdown)
    signal.signal(signal.SIGINT, shutdown)

    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.load_cert_chain(CERT_FILE, KEY_FILE)

    server = HTTPServer((LISTEN_HOST, LISTEN_PORT), ProxyHandler)
    server.socket = context.wrap_socket(server.socket, server_side=True)

    print(f"[proxy] listening on {LISTEN_HOST}:{LISTEN_PORT}", file=sys.stderr)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
